### ISSUE TITLE
files in share_contex25_thresh0 are corrupted? 

### ISSUE THREAD

**Issue by apple2373** [assembly-101/assembly101-action-recognition#12]
I cannot load any of the files in https://github.com/assembly-101/assembly101-action-recognition/tree/main/MS-G3D-action-recognition/HAND_GCN/share_contex25_thresh0/ 

```
import pickle
file_path = "train_label.pkl"
with open(file_path, 'rb') as file:
    data = pickle.load(file)  # or use 'bytes' for byte objects
print(data)
```
will give

Traceback (most recent call last):
  File "temp.py", line 4, in <module>
    data = pickle.load(file)  # or use 'bytes' for byte objects
_pickle.UnpicklingError: pickle data was truncated

```
import numpy as np
file_path = 'train_data_joint_200.npy'
data = np.load(file_path)
print(data)
```
will give 
Traceback (most recent call last):
  File "temp.py", line 3, in <module>
    data = np.load(file_path)
  File "/home/localstorage/miniconda3/envs/py3.7/lib/python3.7/site-packages/numpy/lib/npyio.py", line 441, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/localstorage/miniconda3/envs/py3.7/lib/python3.7/site-packages/numpy/lib/format.py", line 787, in read_array
    array.shape = shape
ValueError: cannot reshape array of size 131040 into shape (46286,3,200,21,2)

~~My access to the original files on Google Drive is not yet approved,  so I cannot reproduce these files either.~~
Update: Now it's approved (thanks!) so I can reproduce these files, but I still think it's better to fix the corrupted files on github, so I keep the issue open.

**Comment by ZahidRazzaq** [comment]
> I cannot load any of the files in https://github.com/assembly-101/assembly101-action-recognition/tree/main/MS-G3D-action-recognition/HAND_GCN/share_contex25_thresh0/
> 
> ```
> import pickle
> file_path = "train_label.pkl"
> with open(file_path, 'rb') as file:
>     data = pickle.load(file)  # or use 'bytes' for byte objects
> print(data)
> ```
> 
> will give
> 
> Traceback (most recent call last): File "temp.py", line 4, in data = pickle.load(file) # or use 'bytes' for byte objects _pickle.UnpicklingError: pickle data was truncated
> 
> ```
> import numpy as np
> file_path = 'train_data_joint_200.npy'
> data = np.load(file_path)
> print(data)
> ```
> 
> will give Traceback (most recent call last): File "temp.py", line 3, in data = np.load(file_path) File "/home/localstorage/miniconda3/envs/py3.7/lib/python3.7/site-packages/numpy/lib/npyio.py", line 441, in load pickle_kwargs=pickle_kwargs) File "/home/localstorage/miniconda3/envs/py3.7/lib/python3.7/site-packages/numpy/lib/format.py", line 787, in read_array array.shape = shape ValueError: cannot reshape array of size 131040 into shape (46286,3,200,21,2)
> 
> ~My access to the original files on Google Drive is not yet approved, so I cannot reproduce these files either.~ Update: Now it's approved (thanks!) so I can reproduce these files, but I still think it's better to fix the corrupted files on github, so I keep the issue open.

**Comment by ZahidRazzaq** [comment]
@apple2373 I faced same issue from https://github.com/assembly-101/assembly101-action-recognition/tree/main/MS-G3D-action-recognition/HAND_GCN/share_contex25_thresh0/ as those files are corrupted. I generated the annotation files by myself. You can do the same by running the preprocess folder files one by one (update file paths too). This way, you will clean annotation files and issue will be resolved.
Thanks
